### ISSUE TITLE
With no pipewire, "ESC Mixer Control" may fill up all pulseaudio connections in seconds and break sound for all apps

### ISSUE THREAD

**Issue by ell1e** [EasyScreenCast/EasyScreenCast#349] opened 2023-07-26 18:40 UTC
## Expected Behavior
even when pipewire becomes unavailable, ESC doesn't ever break pulseaudio sound as a result

## Current Behavior
Sometimes "ESC Mixer Control" will fill up all pulseaudio connections in seconds and break sound for all apps. I think the trigger might be possibly related to pipewire being unavailable which admittedly then renders using the extension kind of moot (but a user might have installed it before that happening). But is still a situation that I suggest might be handled more gracefully. [See here for logs!](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6854)

## Steps to Reproduce (for bugs)

1. Install and enable EasyScreenCast extension, remove pipewire binary, make sure pulseaudio is available as alternative
2. (unsure what exactly then triggers it as additional condition)
3. ESC now hogs pulseaudio daemons and blocks use of it for anything

## Logs

 * Use `journalctl /usr/bin/gnome-shell -f` to monitor Gnome shell activity. Maybe the crash will log something.
 * Log, **enable verbose debug logs** into options window, and after that try  
 `journalctl --since=today --no-pager | grep js`
 * webcam info:
 `v4l2-ctl --all`
 * webcam info:
 `for VIDEO_DEVICE in /dev/video* ; do echo ; echo ; echo $VIDEO_DEVICE ; echo ; v4l2-ctl --device=$VIDEO_DEVICE --list-inputs ; done`
 * webcam info:
 `GST_DEBUG=v4l2src:5 gst-launch-1.0 v4l2src num-buffers=1 ! fakesink | grep probed`

## Your Environment

* Where did you download the extension?
 [x] Gnome shell extension website
 [ ] From Git (Add commit tag)
* Gnome shell version: 43.6

* Operating System and version: Fedora 37

* Display server: Wayland

**Comment by adangel** [comment] 2023-10-09 19:18
One step further in the analysis:
* We create the mixer control here: https://github.com/EasyScreenCast/EasyScreenCast/blob/bb0139a6e0f2f2dfd44da3bb22953999140d5b56/utilaudio.js#L65-L75
* We use it in the main extension here: https://github.com/EasyScreenCast/EasyScreenCast/blob/bb0139a6e0f2f2dfd44da3bb22953999140d5b56/extension.js#L73 and https://github.com/EasyScreenCast/EasyScreenCast/blob/bb0139a6e0f2f2dfd44da3bb22953999140d5b56/extension.js#L482-L483 to populate the menu, where you can select the audio source
* We create the mixer/pulse audio client connection already, when the extension is enabled.
* However, when the extension is disabled, we don't remove the connection, e.g. the following destroy method is not called from anywhere: https://github.com/EasyScreenCast/EasyScreenCast/blob/bb0139a6e0f2f2dfd44da3bb22953999140d5b56/utilaudio.js#L321-L326
* When the extension is enabled again, a new mixer is created. The old mixer is still connected.
* This happens everytime, the extension is enabled.
* The extension is disabled, when the screen is locked and enabled when the screen is unlocked.

I'm unsure yet, how this is connected with pipewire - and I'm hestitating to remove the pipewire binary... Maybe something has triggered so that the gnome shell extensions are enabled and disabled (maybe a crash?).

Note, that without pipewire, the whole extension is useless, as the screen recording is based on pipewire... No pipewire, no screen cast.

**Comment by ell1e** [comment] 2023-10-09 19:21
For testing, it might be enough to just temporarily move/rename the binary, reboot  and do all the testing, then move/rename it back, and reboot again.

**Comment by adangel** [comment] 2023-10-09 19:32
Do you have any logs by any chance? It would be interesting, what gnome-shell logged...

**Comment by adangel** [comment] 2023-10-09 19:50
Ok, so I tried this: in gnome-os you can't manipulate the filesystem (for once, /usr is read-only, but after reboot, it is restored). I had a ubuntu 22.04. When I rename /usr/bin/pipewire -> /usr/bin/pipewire.disabled and restart afterwards, nothing spectacular is happening. Screencast doesn't work anymore as expected (neither via gnome, nor via ESC), but I also didn't notice any additional pulse audio connections (checked with `pactl list client | grep ESC`). There is only one connection after login.

I suspect, something different happened on your machine. But without the original logs, we probably never know.

Since this is not reproducible, all I would fix for this issue is to cleanup the pulse audio connection properly, when the extension is disabled. Otherwise connections might accumulate, if you have a long running desktop session, which you just lock and unlock.

**Comment by ell1e** [comment] 2023-10-09 20:07
I only have the logs I attached [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6854), I moved to a distribution since that doesn't deploy pipewire for users yet (which I'm thankful for given how buggy it usually was for me) so the setup is now considerably different here

**Closed** 2023-10-14 14:34 UTC
Labels: TYPE: bug
