### ISSUE TITLE
There was an error loading the options dialog for EasyScreenCast

### ISSUE THREAD

**Issue by KostyanSigaev** [EasyScreenCast/EasyScreenCast#309] opened 2021-12-25 17:20 UTC
The plugin does not start, and when I open its settings, a terminal window pops up with the text:
Error: Requiring Gst, version 1.0: Typelib file for namespace 'Gst', version '1.0' not found

Stack trace:
  @/home/qwerty/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/utilwebcam.js:16:7
  @/home/qwerty/.local/share/gnome-shell/extensions/EasyScreenCast@iacopodeenosee.gmail.com/prefs.js:33:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  
I have read many solutions to this problem, but none have helped me...
System: Ubuntu 18.04 amd64, Gnome Shell 3.28.4

**Comment by adangel** [comment] 2021-12-25 21:36
"Gst" is gstreamer. The library to access gstreamer from within gnome shell via javascript seems to be missing.
Please install it by executing `sudo apt-get install gir1.2-gstreamer-1.0`

Note: Newer gnome-shell versions already depend on this (e.g. gnome-shell 41). It's maybe worth improving the dependencies information for the debian/ubuntu packages, so that ESC explicitly requires this as well.

Note2: You might be missing more packages, see https://github.com/EasyScreenCast/EasyScreenCast#requirements for some requirements....

**Comment by adangel** [comment] 2022-08-23 16:52
This is a duplicate of #246

**Closed by adangel** 2022-08-23 16:52 UTC
Labels: TYPE: duplicate
